export const FETCH_POSTS_FETCHING = 'FETCH_POSTS_FETCHING'
export const FETCH_POSTS_COMPLETED = 'FETCH_POSTS_COMPLETED'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const FETCH_BOOKS_FETCHING = 'FETCH_BOOKS_FETCHING'
export const FETCH_BOOKS_COMPLETED = 'FETCH_BOOKS_COMPLETED'
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR'